[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cirq_sic"
version = "0.1.0"
dependencies = ["numpy", "scipy", "matplotlib", "cirq", "cirq-google", "qsimcirq", "ipykernel"]